name: Release unibeat-api to Production k8s
on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Publish to Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build image
        run: docker build --platform=linux/amd64 -t unibeat-api .
      - name: Login to container registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag unibeat-api registry.digitalocean.com/ds-services-container/unibeat-api:${{ github.event.release.tag_name }}
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/ds-services-container/unibeat-api:${{ github.event.release.tag_name }}

  deploy:
    name: Configure and deploy to staging
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Authenticate kubectl
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ds-k8s
      - name: Helm Deploy
        run: helm upgrade --install --create-namespace -n prd --set image.tag=${{ github.event.release.tag_name }} --set envPrefix=prd unibeat-api unibeat-api
